// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYAnOrybfeUQhpuh_bdEJseA2S3mATpwY',
    appId: '1:3655845413:web:112d5d9d26ed2d312361cc',
    messagingSenderId: '3655845413',
    projectId: 'medlog-353e6',
    authDomain: 'medlog-353e6.firebaseapp.com',
    storageBucket: 'medlog-353e6.appspot.com',
    measurementId: 'G-8362762TJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIj4CV_b672QNAh5F9FLvNS2b2Sqoi5qc',
    appId: '1:3655845413:android:473970806f77a4192361cc',
    messagingSenderId: '3655845413',
    projectId: 'medlog-353e6',
    storageBucket: 'medlog-353e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1VM2uAIYAbCoL6OMdGKiRwdBMwyZQSE',
    appId: '1:3655845413:ios:020c9fb6b50b86a52361cc',
    messagingSenderId: '3655845413',
    projectId: 'medlog-353e6',
    storageBucket: 'medlog-353e6.appspot.com',
    iosClientId: '3655845413-bllm45eajdkt801jogbio3pfpsv2ju34.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK1VM2uAIYAbCoL6OMdGKiRwdBMwyZQSE',
    appId: '1:3655845413:ios:020c9fb6b50b86a52361cc',
    messagingSenderId: '3655845413',
    projectId: 'medlog-353e6',
    storageBucket: 'medlog-353e6.appspot.com',
    iosClientId: '3655845413-bllm45eajdkt801jogbio3pfpsv2ju34.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlog',
  );
}
